### PR TITLE
chore: webpack bundling support

### PR DESCRIPTION
**Pull request by jogboms**

### CODE REVIEW

**Comment by jogboms** [comment]
@mkloubert noticed this issue today since `nativescript-dev-webpack` doesn't yet support es6.

**Comment by mkloubert** [comment]
@jogboms 

Thanks a lot! :-)

I think, that [this](https://www.npmjs.com/~jogboms) is your account at [npmjs.com](https://www.npmjs.com), right?

**Comment by jogboms** [comment]
Yes. It is. 👍

**Comment by mkloubert** [comment]
Great! Added you as collaborator.

**Pull request merged**
